import 'package:coffe_shop/models/coffee_model.dart';
import 'package:flutter/material.dart';

List<Coffee> dummyCoffee = [
  Coffee(
    id: '1',
    name: '아메리카노',
    type: CoffeeType.espresso,
    imageUrl: 'img/americano_espresso.jpg',
    rating: 4.5,
    participants: 1200,
    description: '에스프레소에 뜨거운 물을 더해 부드러우면서도 깊은 풍미를 가진 기본 커피.',
    price: 4500,
  ),
  Coffee(
    id: '2',
    name: '아몬드 에스프레소',
    type: CoffeeType.espresso,
    imageUrl: 'img/amond_espresso.jpg',
    rating: 4.7,
    participants: 980,
    description: '고소한 아몬드 향과 진한 에스프레소의 조화가 돋보이는 커피.',
    price: 5000,
  ),
  Coffee(
    id: '3',
    name: '카푸치노',
    type: CoffeeType.espresso,
    imageUrl: 'img/cappuchino.jpg',
    rating: 4.6,
    participants: 850,
    description: '부드러운 스팀 밀크와 우유 거품이 더해져 크리미한 식감을 가진 이탈리안 커피.',
    price: 5000,
  ),
  Coffee(
    id: '4',
    name: '콜드 브루',
    type: CoffeeType.coldbrew,
    imageUrl: 'img/coldbrew.jpg',
    rating: 4.8,
    participants: 760,
    description: '12시간 이상 천천히 우려내어 산미와 단맛이 조화를 이루는 부드러운 커피.',
    price: 5500,
  ),
  Coffee(
    id: '5',
    name: '아이스 커피',
    type: CoffeeType.brewdCoffee,
    imageUrl: 'img/icecoffee_brewd.jpg',
    rating: 4.4,
    participants: 690,
    description: '직접 내린 커피를 얼음과 함께 제공해 시원하면서도 깔끔한 맛을 선사하는 커피.',
    price: 5500,
  ),
  Coffee(
    id: '6',
    name: '콘 에스프레소',
    type: CoffeeType.espresso,
    imageUrl: 'img/corn_espresso.jpg',
    rating: 4.6,
    participants: 920,
    description: '고소한 옥수수 향이 은은하게 퍼지는 독특한 풍미의 에스프레소.',
    price: 5800,
  ),
  Coffee(
    id: '7',
    name: '크림 콜드브루',
    type: CoffeeType.coldbrew,
    imageUrl: 'img/cream_coldbrew.jpg',
    rating: 4.9,
    participants: 420,
    description: '콜드브루에 부드러운 크림이 더해져 달콤하고 깊은 풍미가 특징인 커피.',
    price: 6000,
  ),
  Coffee(
    id: '8',
    name: '돌체 콜드브루',
    type: CoffeeType.coldbrew,
    imageUrl: 'img/dolche_coldbrew.jpg',
    rating: 4.7,
    participants: 350,
    description: '연유의 달콤함과 콜드브루의 깊은 맛이 어우러진 부드러운 커피.',
    price: 6500,
  ),
  Coffee(
    id: '9',
    name: '헤이즐넛 에스프레소',
    type: CoffeeType.espresso,
    imageUrl: 'img/heyzlnult_espresso.jpg',
    rating: 4.3,
    participants: 280,
    description: '고소한 헤이즐넛 향이 가미된 달콤한 에스프레소.',
    price: 5500,
  ),
  Coffee(
    id: '10',
    name: '흑임자 콜드브루',
    type: CoffeeType.coldbrew,
    imageUrl: 'img/huk_coldbrew.jpg',
    rating: 4.8,
    participants: 520,
    description: '고소한 흑임자 풍미와 부드러운 콜드브루가 조화로운 커피.',
    price: 6000,
  ),
  Coffee(
    id: '11',
    name: '프라푸치노',
    type: CoffeeType.frappuccino,
    imageUrl: 'img/prapuchino.jpg',
    rating: 4.8,
    participants: 520,
    description: '에스프레소, 우유, 얼음을 블렌딩하여 달콤하고 시원한 맛을 제공하는 커피.',
    price: 6000,
  ),
  Coffee(
    id: '12',
    name: '딸기 프라푸치노',
    type: CoffeeType.frappuccino,
    imageUrl: 'img/straw_blen.jpg',
    rating: 4.8,
    participants: 520,
    description: '신선한 딸기와 우유를 블렌딩하여 상큼하고 달콤한 맛이 특징인 음료.',
    price: 6000,
  ),
  Coffee(
    id: '13',
    name: '자바칩 프라푸치노',
    type: CoffeeType.frappuccino,
    imageUrl: 'img/zava_fra.jpg',
    rating: 4.8,
    participants: 520,
    description: '초콜릿 칩과 에스프레소가 어우러져 달콤하면서도 씹는 재미가 있는 커피.',
    price: 6000,
  ),
  Coffee(
    id: '14',
    name: '레몬 블렌디드',
    type: CoffeeType.blended,
    imageUrl: 'img/lemon_blen.jpg',
    rating: 4.8,
    participants: 520,
    description: '상큼한 레몬과 얼음을 함께 블렌딩하여 청량한 맛을 선사하는 음료.',
    price: 6000,
  ),
  Coffee(
    id: '15',
    name: '망고 블렌디드',
    type: CoffeeType.blended,
    imageUrl: 'img/mango_blen.jpg',
    rating: 4.8,
    participants: 520,
    description: '달콤한 망고를 가득 담아 열대과일의 풍미를 느낄 수 있는 음료.',
    price: 6000,
  ),
  Coffee(
    id: '16',
    name: '딸기 블렌디드',
    type: CoffeeType.blended,
    imageUrl: 'img/straw_blen.jpg',
    rating: 4.8,
    participants: 520,
    description: '신선한 딸기와 얼음을 블렌딩하여 상큼하고 시원한 맛을 선사하는 음료.',
    price: 6000,
  ),
  Coffee(
    id: '17',
    name: '캐모마일 티',
    type: CoffeeType.tea,
    imageUrl: 'img/camo_tea.jpg',
    rating: 4.8,
    participants: 520,
    description: '은은한 허브 향과 부드러운 맛이 특징인 캐모마일 꽃잎 차.',
    price: 6000,
  ),
  Coffee(
    id: '18',
    name: '얼그레이 티',
    type: CoffeeType.tea,
    imageUrl: 'img/grey_tea.jpg',
    rating: 4.8,
    participants: 520,
    description: '베르가못 오일의 향이 더해진 우아하고 깊은 맛의 홍차.',
    price: 6000,
  ),
  Coffee(
    id: '19',
    name: '말차 티',
    type: CoffeeType.tea,
    imageUrl: 'img/malch_tea.jpg',
    rating: 4.8,
    participants: 520,
    description: '진한 녹차 분말을 사용하여 부드러우면서도 쌉싸름한 맛이 특징인 말차 티.',
    price: 6000,
  ),
  Coffee(
    id: '20',
    name: '민트 티',
    type: CoffeeType.tea,
    imageUrl: 'img/mint_tea.jpg',
    rating: 4.8,
    participants: 520,
    description: '상쾌한 민트 향이 퍼지며 깔끔한 끝맛을 자랑하는 허브 티.',
    price: 6000,
  ),
];
